#!/bin/sh
#
# Regenerate ModemManager's ignore list from luci-app-5gmodem's configuration.
#
# Any modem this app drives over a KERNEL protocol (qmi/mbim/xmm/ncm/atc/3g/
# wwan/ppp/fibocom) must be hidden from ModemManager. Otherwise MM fights the
# kernel for the modem, crash-loops on it, and its port probing corrupts our AT
# reads (metrics), band writes (CNBP) and USSD (+CUSD replies). Modems on the
# 'modemmanager' protocol are deliberately left visible so MM manages them.
#
# The rule set is derived from each modem's ACTIVE protocol, so it follows the
# user's choices. It is regenerated on install, on every boot (via the resolve
# hotplug) and whenever an interface is (re)created (mkiface) - so it stays in
# sync and, living in /etc/udev/rules.d, is applied by udevd at cold-plug on
# every subsequent boot (this is what makes the fix survive a reflash/reboot).

RES=/usr/share/5gmodem
RULE=/etc/udev/rules.d/99-5gmodem-mm-ignore.rules
CFG=5gmodem

# protocols where the kernel (not ModemManager) owns the modem
_is_kernel_proto() {
	case "$1" in
		qmi|mbim|xmm|ncm|atc|3g|wwan|ppp|fibocom) return 0 ;;
		*) return 1 ;;
	esac
}

# effective protocol of the modem at usb path $1: prefer the real network
# interface proto, fall back to the remembered iface_proto
_proto_for_path() {
	SEC="m_$(echo "$1" | sed 's/[^A-Za-z0-9]/_/g')"
	IF=$(uci -q get "$CFG.$SEC.network")
	if [ -n "$IF" ]; then
		NP=$(uci -q get "network.$IF.proto")
		[ -n "$NP" ] && { echo "$NP"; return; }
	fi
	uci -q get "$CFG.$SEC.iface_proto"
}

TMP="${RULE}.tmp.$$"
{
	echo "# Auto-generated by luci-app-5gmodem (mm-filter.sh) - do not edit."
	echo "# Modems driven via a kernel proto are hidden from ModemManager so it"
	echo "# does not fight the kernel and corrupt AT reads / metrics / USSD."
} > "$TMP"

IGNORED_VP=""
IGNORED_PATHS=""
for P in $("$RES/listmodems.sh" 2>/dev/null | jsonfilter -e '@[*].path' 2>/dev/null); do
	[ -n "$P" ] || continue
	VIDPID=$("$RES/listmodems.sh" 2>/dev/null | jsonfilter -e "@[@.path=\"$P\"].vidpid" 2>/dev/null | head -1)
	[ -n "$VIDPID" ] || continue
	PROTO=$(_proto_for_path "$P")
	_is_kernel_proto "$PROTO" || continue
	case " $IGNORED_VP " in *" $VIDPID "*) ;; *)
		IGNORED_VP="$IGNORED_VP $VIDPID"
		VID="${VIDPID%%:*}"; PID="${VIDPID##*:}"
		echo "ATTRS{idVendor}==\"$VID\", ATTRS{idProduct}==\"$PID\", ENV{ID_MM_DEVICE_IGNORE}=\"1\"" >> "$TMP"
		;;
	esac
	IGNORED_PATHS="$IGNORED_PATHS $P"
done

# nothing changed -> leave the file (and udev) alone
if cmp -s "$TMP" "$RULE" 2>/dev/null; then
	rm -f "$TMP"
	exit 0
fi

mkdir -p /etc/udev/rules.d
mv "$TMP" "$RULE"

# Best-effort runtime application. udevd applies the rule at the next cold-plug
# (boot) regardless; if udevadm is present we can also apply it now. As a final
# safety net, stop ModemManager if it is running while a kernel-proto modem is
# present but nothing needs MM - the app's apply_mm_state does this too, but
# doing it here keeps the two in lockstep after a proto change.
if command -v udevadm >/dev/null 2>&1; then
	udevadm control --reload-rules >/dev/null 2>&1
	udevadm trigger >/dev/null 2>&1
fi

exit 0
